spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:auth-service-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /auth-service-db
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  public-key: classpath:app.pub
  private-key: classpath:app.key

springdoc:
  api-docs:
    path: /api/v1/auth/api-docs
server:
  port: 0
